### ISSUE TITLE
Webkit uses too much CPU and Memory

### ISSUE THREAD

**Issue by rmad17** [tiliado/nuvola-app-8tracks#1]
I use the 8tracks app daily, but I wasn't sure whether the issue is with the Nuvola Player 3 or the 8tracks app so I will be reporting the issue in here first. If I do not receive a response I will post it in the nuvola 3 repo (again since I am not sure if its an issue with the app or Nuvola)
![nuvola](https://cloud.githubusercontent.com/assets/2450047/10157923/e4f88eea-66ab-11e5-8140-94d379375cee.png)

For info:
I am running Linux Mint 17.2(based on Ubuntu 14.04) 64 bit. 
Also my system has 8GB of RAM. Considering that its consuming a huge amount of ram. It won't consume this much if I ran it in one tab of Chrome or Firefox.
Please let me know if you are aware of the issue.

**Comment by fenryxo** [comment]
Hello @rmad17. Thanks for taking the time for reporting this issue. Memory usage in your case is pretty high indeed. For example, there is memory consumption of Deezer web app after several days running on my system: 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
19502 fenryxo   20   0 3739248 187584  35752 S  26.8  1.2  61:14.39 WebKitWebProces
(187584 - 35752)/1000 = 152 MB for Deezer web page in WebKit, reasonable
19463 fenryxo   20   0 2956340   62440 40864 S   6.8  0.4  13:13.96 nuvolaplayer3-d
(62440 - 40864)/1000 = 22 MB for Nuvola Player, pretty good
19687 fenryxo   20   0 2398208  80836  24496 S   5.9  0.5  47:14.45 WebKitPluginPro
(80836 - 24496)/1000 = 57 MB for Flash plugin, blah
``` 
Initial memory usage for 8tracks web app on my system is:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
22086 fenryxo   20   0 3707556 180568  72984 R  17.9  1.1   0:07.36 WebKitWebProces
(180568 - 72984)/1000 = 108 MB for a fresh 8tracks web page in WebKit, reasonable
22133 fenryxo   20   0 2024752  58152  44860 S   6.8  0.4   0:01.47 WebKitPluginPro
(58152 - 44860)/1000 = 14 MB for Flash plugin, awesome
22076 fenryxo   20   0 2825088  70176  48764 S   3.5  0.4   0:01.96 nuvolaplayer3-8
(70176 - 48764)/1000 = 22 MB for Nuvola Player, pretty good
```

I will keep running 8tracks in background and watch memory usage closer. I have a few wuestions for you:

1. What's intital memory usage 8tracks web app on your system?
2. How long it takes to achieve similar memory usage as in your report?
3. What's memory usage in a fresh Firefox/Chrome instance with 8tracks and without any other pages?

**Comment by rmad17** [comment]
I just tried out running 8tracks on Chrome without any other tab and it consumed around 1.7 to 2.2 % memory usage. However CPU usage was very high - 15%. I am sorry but I cannot try closing all tabs in Firefox since I will lose a lot of work. I am using firefox 41 just for info. I did try using 8tracks with firefox with all other tabs and the memory consumption increase was negligible. However the CPU consumption shot up by 40-50%.
In case of Nuvola it only takes a few hours to shot up to such high levels of memory usage.
I hope I answered all your queries to the best of my knowledge. If you have any more questions please ask.

**Comment by fenryxo** [comment]
> I just tried out running 8tracks on Chrome without any other tab and it consumed around 1.7 to 2.2 %

So it's around 170 MB. Comparable with Nuvola Player + 8tracks on my system.

> In case of Nuvola it only takes a few hours to shot up to such high levels of memory usage.

Is the same memory usage reproducible also in WebKitGTK MiniBrowser? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by fenryxo** [comment]
For you information, the memory usage of 8tracks web app launched on Tue September 29 is now:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
22086 fenryxo   20   0 4343896 317632  41724 R  15.6  2.0 141:32.14 WebKitWebProces
(317632 - 41724)/1000 = 276 MB
22133 fenryxo   20   0 2058068  42640  15116 S   9.2  0.3  73:16.49 WebKitPluginPro
(42640 - 15116)/1000 = 28 MB
22076 fenryxo   20   0 2841772  59004  21028 S   3.9  0.4  31:54.91 nuvolaplayer3-8
(59004 - 21028)/1000 = 38 MB
```

**Comment by fenryxo** [comment]
Hello. I'm closing this ticket as I haven't received any response to my request for more information posted on October 2nd, 2015. If the issue still persists, feel free to post missing information and reopen this issue.
